name: exatrkx
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py36_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py36_1000
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py36h24bf2e0_0
  - ipython=7.5.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py_0
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.6=py36_0
  - jupyterlab_server=0.2.0=py_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markupsafe=1.1.1=py36h14c3975_0
  - mistune=0.8.4=py36h14c3975_1000
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - notebook=5.7.8=py36_1
  - numpy-base=1.17.2=py36hde5b4d6_0
  - openssl=1.1.1c=h516909a_0
  - pandoc=2.7.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.4.0=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.1.1=py36_0
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.4.2=py_0
  - pyrsistent=0.15.2=py36h516909a_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pyzmq=18.0.1=py36hc4ba49a_1
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py36h516909a_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=hf484d3e_1000
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - cloudpickle==1.1.1
    - colorama==0.4.1
    - contextlib2==0.6.0
    - cycler==0.10.0
    - dm-sonnet==1.35
    - future==0.17.1
    - gast==0.2.2
    - google-pasta==0.1.7
    - graph-nets==1.0.5.dev0
    - grpcio==1.21.1
    - h5py==2.8.0
    - joblib==0.13.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - llvmlite==0.29.0
    - markdown==3.1.1
    - matplotlib==3.1.0
    - mock==3.0.5
    - mpi4py==3.0.0
    - networkx==2.3
    - numba==0.44.0
    - numexpr==2.6.9
    - numpy==1.16.4
    - pandas==0.24.2
    - pillow==6.0.0
    - protobuf==3.8.0
    - pyparsing==2.4.0
    - pytz==2019.1
    - pyyaml==5.1
    - scikit-learn==0.21.2
    - scipy==1.3.0
    - semantic-version==2.8.2
    - six==1.12.0
    - sklearn==0.0
    - tables==3.4.4
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.0
    - tensorflow-gpu==1.15.0
    - tensorflow-probability==0.8.0
    - termcolor==1.1.0
    - torch==1.0.1
    - torchvision==0.2.1
    - werkzeug==0.15.4
    - wrapt==1.11.2
prefix: ~/.conda/envs/exatrkx

