# Input/output configuration
input_dir: ./inputdata/train_100_events
output_dir: ./out/hitgraphs_100
n_files: 100

# Graph building configuration
selection:
    pt_min: 0. # GeV
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 8
    n_eta_sections: 2
    eta_range: [-5, 5]
